apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_NAME
          value: interactivelabs
        - name: POSTGRES_PASSWORD
          value: '!nt3r@ct!v3l@bs'
        - name: POSTGRES_USER
          value: interactivelabs
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgredb
      restartPolicy: Always
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-claim