apiVersion: v1
kind: ServiceAccount
metadata:
  name: webserver
automountServiceAccountToken: true
---
apiVersion: v1
kind: Secret
metadata:
  name: webserver-secret
  annotations:
    kubernetes.io/service-account.name: webserver
type: kubernetes.io/service-account-token