apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ssh-server
  name: ssh-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ssh-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: ssh-server
    spec:
      containers:
      - args:
        - bash
        - -c
        - service ssh restart && tail -F anything
        image: ubuntu:ssh
        imagePullPolicy: ""
        name: ssh-server
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
