apiVersion: v1
kind: Pod 
metadata:
  labels:
    app: studentno
  name: studentno
spec:
  containers:
  - name: ubuntustudent
    command: ["/bin/bash", "-c", "service ssh start && tail -F anything"]
    image: kwendim/ubuntu:ssh
