apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web
    spec:
      serviceAccountName: webserver
      hostAliases:
          - ip: "127.0.0.1"
            hostnames:
              - "db"
      containers:
      - name: db
        env:
        - name: POSTGRES_NAME
          value: interactivelabs
        - name: POSTGRES_PASSWORD
          value: '!nt3r@ct!v3l@bs'
        - name: POSTGRES_USER
          value: interactivelabs
        image: postgres
      - name: web
        command: ["/bin/bash","-c", "sleep 15 && python /code/manage.py migrate && python /code/manage.py runserver 0:8000"]
        image: kwendim/web:0.1
        #imagePullPolicy: Always
        ports:
        - containerPort: 8000
      restartPolicy: Always
status: {}
