kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres-volume
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/postgresdata"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: webhook-pv-volume
  labels:
    type: local
    app: webhook-volume
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/webhook"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: webhook-claim
  name: webhook-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  selector: 
    matchLabels:
      type: local
      app: webhook-volume
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-claim
  labels:
    app: postgres-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels:
      type: local
      app: postgres-volume