apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: webhook-claim
  name: webhook-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}