# Generated by Django 3.0.4 on 2020-03-23 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=4096)),
                ('git_webhook', models.CharField(max_length=300)),
                ('secret', models.CharField(max_length=20)),
                ('private_key', models.CharField(max_length=6000)),
            ],
        ),
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=4096)),
                ('number_of_tasks', models.IntegerField()),
                ('location', models.CharField(max_length=1000)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField()),
                ('tasks_completed', models.IntegerField()),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.Labs')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student_id', 'lab_id')},
            },
        ),
        migrations.CreateModel(
            name='CourseToLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.Courses')),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.Labs')),
            ],
            options={
                'unique_together': {('course_id', 'lab_id')},
            },
        ),
        migrations.CreateModel(
            name='CourseOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.Courses')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('course_id', 'user_id')},
            },
        ),
    ]
