# Generated by Django 3.0.4 on 2020-03-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseownership',
            name='role',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='git_webhook',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='location',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='private_key',
            field=models.CharField(max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='secret',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
