# Generated by Django 3.0.4 on 2020-03-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_auto_20200323_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseownership',
            name='role',
            field=models.CharField(blank=True, default='student', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courses',
            name='git_webhook',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='courses',
            name='location',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='courses',
            name='private_key',
            field=models.CharField(blank=True, max_length=6000),
        ),
        migrations.AlterField(
            model_name='courses',
            name='secret',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
